
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 18 23:43:27 CEST 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PRINTTOF = 62;
  public static final int INTERROGACION = 44;
  public static final int PARENTESIS_CIERRE = 23;
  public static final int RET = 30;
  public static final int OTHER = 33;
  public static final int PRINTDEC = 60;
  public static final int DIFERENTE = 10;
  public static final int RESTA = 5;
  public static final int PUNTOCOMA = 47;
  public static final int ARRAY = 42;
  public static final int REG = 43;
  public static final int REF = 37;
  public static final int NOT = 17;
  public static final int AND = 15;
  public static final int IGUAL = 9;
  public static final int CORCHETE_CIERRE = 25;
  public static final int STARTPLS = 41;
  public static final int FUN = 3;
  public static final int TODEC = 63;
  public static final int READNUM = 57;
  public static final int OR = 16;
  public static final int BOOK = 38;
  public static final int DOSPUNTOSIGUAL = 51;
  public static final int NUM = 45;
  public static final int SUMA = 4;
  public static final int TYPEDEF = 50;
  public static final int EOF = 0;
  public static final int CORCHETE_APERTURA = 24;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int MODULO = 8;
  public static final int CHECK = 31;
  public static final int MENOR = 13;
  public static final int TRU = 55;
  public static final int PUNTERO = 19;
  public static final int ASIGNACION = 18;
  public static final int MAYOR = 14;
  public static final int READTOF = 61;
  public static final int PRINTNUM = 59;
  public static final int NUMERO_DECIMAL = 54;
  public static final int DEV = 29;
  public static final int ACCESOCAMPO = 49;
  public static final int PUNTO = 26;
  public static final int LLAVE_APERTURA = 20;
  public static final int IDEN = 52;
  public static final int TOF = 2;
  public static final int FINAL = 28;
  public static final int MAYOR_IGUAL = 12;
  public static final int CONSTRUCTOR = 48;
  public static final int DURING = 35;
  public static final int OTHER_CHECK = 32;
  public static final int READDEC = 58;
  public static final int LLAVE_CIERRE = 21;
  public static final int TONUM = 64;
  public static final int NOTHING = 40;
  public static final int PARENTESIS_APERTURA = 22;
  public static final int DEC = 46;
  public static final int UNBOOK = 39;
  public static final int MENOR_IGUAL = 11;
  public static final int FOLS = 56;
  public static final int CYCLE = 34;
  public static final int ENTITY = 36;
  public static final int DIVISION = 7;
  public static final int NUMERO_ENTERO = 53;
  public static final int MULTIPLICACION = 6;
}

