package ast;

public enum KindAsig{
	ASIGNACION, ACCESO, PUNTERO, INTERROGACION, AND, OR, CORCHETE, PARENTESIS, LLAVE, POR, MOD, DIV, MAS, MENOS, MAYOR, MENOR, MAYOR_IGUAL, MENOR_IGUAL, EQ, NEQ, NOT;
}